.TH 42sh 1

.SH NAME

42sh

.SH SYNOPSIS

The answer to this is very simple," Adams said. "It was a joke. It had to be a number, an ordinary, smallish number, and I chose that one. Binary representations, base 13, Tibetan monks are all complete nonsense. I sat on my desk, stared in to the garden and thought 42 will do. I typed it out. End of story.

.SH DESCRIPTION

Bash implementation over the course of 1 month by 4 third year student @EPITA.

.SH FEATURES

.PP
* Interactive mode, run script mode
.PP
* Options parsing
.PP
* AST building
.PP
* AST execution
.PP
* AST dot printing

.SH AUTHORS

alexandre.lyfound
arthur.pannier
julien.chau
victor.coatalem
